### ISSUE TITLE
Mark twig function `sulu_seo` as deprecated

### ISSUE THREAD

**Issue by trickreich** [sulu/sulu-docs#338]

**Comment by danrot** [comment]
@alexander-schranz Does the documentation describe anywhere how to properly include the twig template instead of using the twig function? Then we could also add a deprecate header and link to that part of the documentation. That would affect these two pages: 

* https://github.com/sulu/sulu-docs/blob/1edf358/reference/twig-extensions/functions/sulu_seo.rst
* https://github.com/sulu/sulu-docs/blob/1edf358/reference/twig-extensions/functions/sulu_meta_seo.rst (already marked as deprecated, but links to the other deprecated function).

**Comment by wachterjohannes** [comment]
@danrot there is only a mention in a bigger docs-page "Rendering Pages with Twig" http://docs.sulu.io/en/latest/book/twig.html?highlight=seo.html.twig maybe we should introduce a new page which describes this `seo.html.twig` and other seo optimizations.
