### ISSUE TITLE
Sulu 1.6.21 (current latest release) requires abandoned guzzle/guzzle

### ISSUE THREAD

**Issue by sigbits** [sulu/sulu-docs#389]
Sulu 1.6.21 requires` friendsofsymfony/http-cache`, which requires `guzzle/guzzle` which is abandoned.

`composer why guzzle/guzzle`
`friendsofsymfony/http-cache  1.4.5  requires  guzzle/guzzle (~3.8)`

`composer why friendsofsymfony/http-cache`
`sulu/sulu  1.6.21  requires  friendsofsymfony/http-cache (~1.4)`

Solution: upgrade to a higher (major) version of friendsofsymfony/http-cache

**Comment by alexander-schranz** [comment]
Hello @sigbits,
thank you for creating this issue.
The 1.x version of sulu will not support fos-http-cache 2.0 because of bc breaks.
In the current development version of sulu (2.0-alpha) the fos-http-cache is updated, see current [composer.json](https://github.com/sulu/sulu/blob/9a5fe248e90c496bc8af6dd99226a9d8e75c25dd/composer.json#L29), so there the warning should not longer appear.

**Comment by danrot** [comment]
Since we have updated that in the latest alpha release I am going to close that issue. Thanks for reporting! :+1:
